### ISSUE TITLE
Posts without tags

### ISSUE THREAD

**Issue by acyuta108** [nkmk/hexo-list-related-posts#1]
'hexo generate' raises exception if a post has not tags.

**Comment by nkmk** [comment]
Thank you for your report but I can't reproduce this error.
I tried to make new blog as below.

```sh
$ hexo init
$ hexo --version
hexo: 3.3.7
hexo-cli: 1.0.3
os: Darwin 16.6.0 darwin x64
http_parser: 2.7.0
node: 8.1.2
v8: 5.8.283.41
uv: 1.12.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
openssl: 1.0.2l
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j

$ npm install hexo-list-related-posts
# add <%- list_related_posts() %> to article.ejs
$ hexo generate
```

No error occurred, initial post that has no tags showed "No related post" as expected.

**Comment by gorootde** [comment]
I get the same error:

```
Unhandled rejection TypeError: .../themes/clean-blog/layout/post.ejs:1
 >> 1| <%- partial('_partial/article-full', {item: page}) %>
    2| 

.../themes/clean-blog/layout/_partial/article-full.ejs:84
    82| 
    83| 
 >> 84| <%- list_related_posts(item,{maxCount: 10, orderBy: 'random'}) %>
    85|             <!-- Comments -->
    86|             <% if (item.comment != false) { %>
    87|                 <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

Cannot read property 'tags' of undefined
    at Object.listRelatedPosts (.../node_modules/hexo-list-related-posts/lib/index.js:70:13)
    at Object.wrapper [as list_related_posts] (.../node_modules/lodash/lodash.js:4968:19)
    at eval (eval at compile (.../node_modules/ejs/lib/ejs.js:549:12), <anonymous>:125:17)
    at returnedFn (.../node_modules/ejs/lib/ejs.js:580:17)
    at Theme._View.View._compiledSync (.../node_modules/hexo/lib/theme/view.js:122:20)
    at Theme._View.View.View.renderSync (.../node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (.../node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper [as partial] (.../node_modules/lodash/lodash.js:4968:19)
    at eval (eval at compile (.../node_modules/ejs/lib/ejs.js:549:12), <anonymous>:9:17)
    at returnedFn (.../node_modules/ejs/lib/ejs.js:580:17)
    at Theme._View.View._compiled (.../node_modules/hexo/lib/theme/view.js:127:30)
    at Theme._View.View.View.render (.../node_modules/hexo/lib/theme/view.js:29:15)
    at .../node_modules/hexo/lib/hexo/index.js:390:29
    at tryCatcher (.../node_modules/bluebird/js/release/util.js:16:23)
    at .../node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (.../node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:442:10)
    at resume_ (_stream_readable.js:822:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
All my pages have at least one tag. Seems like `this.post` is undefined.

**Comment by gorootde** [comment]
Workaround: I wrapped the Plugin call in a dedicated partitial template file, and manually added the "post" variable as argument.
